#Docker
#Build a Docker image

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'busybox-latest'
    steps:
    - task: Docker@2
      displayName:  Build and Push
      inputs:
        command: buildAndPush
        containerRegistry: pruebas-azure
        respository: pedrlopez/pruebas-azure