#Docker
#Build a Docker image

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Login to my test pruebas-azure
      inputs:
        command: login
        containerRegistry: 'https://hub.docker.com/repository/docker/pedrlopez/pruebas-azure'
    - task: Docker@2
      displayName:  Build and Push
      inputs:
        command: buildAndPush
        containerRegistry: 'https://hub.docker.com/repository/docker/pedrlopez/pruebas-azure'
        dockerfile: 'app/Dockerfile'
        respository: pedrlopez/pruebas-azure
        tags: |
          $(tag)
